# Generated by Django 5.2.8 on 2025-12-03 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=100)),
                ('gmail', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('plantaFav', models.CharField(max_length=100)),
            ],
        ),
    ]
