# Generated by Django 5.2.8 on 2025-12-04 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='gmail',
            field=models.EmailField(max_length=100),
        ),
    ]
